# Generated by Django 5.2.4 on 2025-07-29 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercial', '0002_alter_clientes_pagina'),
        ('proveedor', '0003_alter_prenda_categorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCalculadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor_select', models.BooleanField(default=False)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('forro', models.CharField(blank=True, choices=[('Blue jean clasico hombre', 'Blue jean clasico hombre'), ('Blue jean pretina anatomica', 'Blue jean pretina anatomica'), ('Pantalon hombre', 'Pantalon hombre'), ('Pantalon dama', 'Pantalon dama')], max_length=100)),
                ('lavado', models.CharField(blank=True, choices=[('Blue jean clasico hombre', 'Blue jean clasico hombre'), ('Blue jean pretina anatomica', 'Blue jean pretina anatomica'), ('Pantalon hombre', 'Pantalon hombre'), ('Pantalon dama', 'Pantalon dama')], max_length=100)),
                ('bordado', models.JSONField(blank=True, null=True)),
                ('estampado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cinta', models.JSONField(blank=True, null=True)),
                ('pegado', models.JSONField(blank=True, null=True)),
                ('cierre', models.JSONField(blank=True, null=True)),
                ('broche', models.JSONField(blank=True, null=True)),
                ('elastico', models.JSONField(blank=True, null=True)),
                ('boton', models.JSONField(blank=True, null=True)),
                ('fusionado', models.CharField(blank=True, choices=[('Camisa manga larga (Cuello + Banda + Perilla + Puños)', 'Camisa manga larga (Cuello + Banda + Perilla + Puños)'), ('Blusa manda 3/4 (Cuello + Banda + Perilla + Puños)', 'Blusa manda 3/4 (Cuello + Banda + Perilla + Puños)'), ('Pantalón súper vértigo', 'Pantalón súper vértigo')], max_length=100)),
                ('confeccion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('plantrel', models.JSONField(blank=True, null=True)),
                ('velcro', models.JSONField(blank=True, null=True)),
                ('sesgo', models.JSONField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('precio_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('calculadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cotizaciones.calculadora')),
                ('prenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedor.prenda')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedor.proveedor')),
            ],
        ),
    ]
