# Generated by Django 5.2.5 on 2025-08-12 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercial', '__first__'),
        ('proveedor', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Proveedor_select', models.BooleanField(default=False)),
                ('Cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Descripcion', models.CharField(blank=True, max_length=100)),
                ('PrecioTela', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('PromedioTela', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('AjusteTela', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('CostoTela', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Forro', models.CharField(blank=True, choices=[('Blue jean clasico hombre', 'Blue jean clasico hombre'), ('Blue jean pretina anatomica', 'Blue jean pretina anatomica'), ('Pantalon hombre', 'Pantalon hombre'), ('Pantalon dama', 'Pantalon dama')], max_length=100)),
                ('Lavado', models.CharField(blank=True, choices=[('Blue jean clasico hombre', 'Blue jean clasico hombre'), ('Blue jean pretina anatomica', 'Blue jean pretina anatomica'), ('Pantalon hombre', 'Pantalon hombre'), ('Pantalon dama', 'Pantalon dama')], max_length=100)),
                ('Bordado', models.JSONField(blank=True, null=True)),
                ('Estampado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Cinta', models.JSONField(blank=True, null=True)),
                ('Pegado', models.JSONField(blank=True, null=True)),
                ('Cierre', models.JSONField(blank=True, null=True)),
                ('Broche', models.JSONField(blank=True, null=True)),
                ('Elastico', models.JSONField(blank=True, null=True)),
                ('Boton', models.JSONField(blank=True, null=True)),
                ('Fusionado', models.CharField(blank=True, choices=[('Camisa manga larga (Cuello + Banda + Perilla + Puños)', 'Camisa manga larga (Cuello + Banda + Perilla + Puños)'), ('Blusa manda 3/4 (Cuello + Banda + Perilla + Puños)', 'Blusa manda 3/4 (Cuello + Banda + Perilla + Puños)'), ('Pantalón súper vértigo', 'Pantalón súper vértigo')], max_length=100)),
                ('Confeccion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Plantrel', models.JSONField(blank=True, null=True)),
                ('Velcro', models.JSONField(blank=True, null=True)),
                ('Sesgo', models.JSONField(blank=True, null=True)),
                ('Extra', models.JSONField(blank=True, null=True)),
                ('Precio_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedor.proveedor')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.clientes')),
                ('prenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedor.prenda')),
            ],
        ),
    ]
