# Generated by Django 5.2.4 on 2025-07-10 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercial', '__first__'),
        ('proveedor', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Proveedor_select', models.BooleanField(default=False)),
                ('Forro', models.CharField(blank=True, choices=[('Blue jean clasico hombre', 'Blue jean clasico hombre'), ('Blue jean pretina anatomica', 'Blue jean pretina anatomica'), ('Pantalon hombre', 'Pantalon hombre'), ('Pantalon dama', 'Pantalon dama')], max_length=100)),
                ('Lavado', models.CharField(blank=True, choices=[('Blue jean clasico hombre', 'Blue jean clasico hombre'), ('Blue jean pretina anatomica', 'Blue jean pretina anatomica'), ('Pantalon hombre', 'Pantalon hombre'), ('Pantalon dama', 'Pantalon dama')], max_length=100)),
                ('Bordado', models.JSONField(blank=True, null=True)),
                ('Estampado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Cinta', models.JSONField(blank=True, null=True)),
                ('Pegado', models.JSONField(blank=True, null=True)),
                ('Cierre', models.JSONField(blank=True, null=True)),
                ('Broche', models.JSONField(blank=True, null=True)),
                ('Elastico', models.JSONField(blank=True, null=True)),
                ('Boton', models.JSONField(blank=True, null=True)),
                ('Fusionado', models.CharField(blank=True, choices=[('Camisa manga larga', 'Blue jean clasico hombre'), ('Blue jean pretina anatomica', 'Blue jean pretina anatomica'), ('Pantalon hombre', 'Pantalon hombre'), ('Pantalon dama', 'Pantalon dama')], max_length=100)),
                ('Proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedor.proveedor')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.clientes')),
                ('prenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedor.prenda')),
            ],
        ),
    ]
