# Generated by Django 5.2.4 on 2025-07-29 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
        ('proveedor', '0003_alter_prenda_categorias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculadora',
            name='creado_en',
        ),
        migrations.AddField(
            model_name='calculadora',
            name='AjusteTela',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='calculadora',
            name='Bordado',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculadora',
            name='Boton',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculadora',
            name='Broche',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculadora',
            name='Cantidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='calculadora',
            name='Cierre',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculadora',
            name='Cinta',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculadora',
            name='Confeccion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='calculadora',
            name='CostoTela',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='calculadora',
            name='Descripcion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='calculadora',
            name='Elastico',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculadora',
            name='Estampado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='calculadora',
            name='Extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculadora',
            name='Forro',
            field=models.CharField(blank=True, choices=[('Blue jean clasico hombre', 'Blue jean clasico hombre'), ('Blue jean pretina anatomica', 'Blue jean pretina anatomica'), ('Pantalon hombre', 'Pantalon hombre'), ('Pantalon dama', 'Pantalon dama')], max_length=100),
        ),
        migrations.AddField(
            model_name='calculadora',
            name='Fusionado',
            field=models.CharField(blank=True, choices=[('Camisa manga larga (Cuello + Banda + Perilla + Puños)', 'Camisa manga larga (Cuello + Banda + Perilla + Puños)'), ('Blusa manda 3/4 (Cuello + Banda + Perilla + Puños)', 'Blusa manda 3/4 (Cuello + Banda + Perilla + Puños)'), ('Pantalón súper vértigo', 'Pantalón súper vértigo')], max_length=100),
        ),
        migrations.AddField(
            model_name='calculadora',
            name='Lavado',
            field=models.CharField(blank=True, choices=[('Blue jean clasico hombre', 'Blue jean clasico hombre'), ('Blue jean pretina anatomica', 'Blue jean pretina anatomica'), ('Pantalon hombre', 'Pantalon hombre'), ('Pantalon dama', 'Pantalon dama')], max_length=100),
        ),
        migrations.AddField(
            model_name='calculadora',
            name='Pegado',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculadora',
            name='Plantrel',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculadora',
            name='PrecioTela',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='calculadora',
            name='Precio_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='calculadora',
            name='PromedioTela',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='calculadora',
            name='Proveedor',
            field=models.ForeignKey(default=321, on_delete=django.db.models.deletion.CASCADE, to='proveedor.proveedor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculadora',
            name='Proveedor_select',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calculadora',
            name='Sesgo',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculadora',
            name='Velcro',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculadora',
            name='prenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedor.prenda'),
        ),
        migrations.DeleteModel(
            name='ItemCalculadora',
        ),
    ]
