# Generated by Django 5.2.4 on 2025-07-10 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nit', models.CharField(max_length=100)),
                ('Nombre', models.CharField(max_length=255)),
                ('Telefono', models.CharField(max_length=20)),
                ('Direccion', models.CharField(max_length=255)),
                ('Ciudad', models.CharField(max_length=100)),
                ('Contacto', models.CharField(max_length=100)),
                ('Correo', models.EmailField(max_length=100)),
                ('Movil', models.CharField(max_length=20)),
                ('Plazo', models.PositiveIntegerField()),
                ('Descuento', models.CharField(blank=True, max_length=100, null=True)),
                ('Contado', models.CharField(choices=[('contado', 'De Contado'), ('desconocido', 'Desconocido')], default='desconocido', max_length=20)),
                ('Categorias', models.TextField(blank=True)),
                ('Textilera', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Imagen', models.ImageField(upload_to='prendas/')),
                ('descripcion', models.TextField()),
                ('Referencia_color_talla_Costo_precio', models.JSONField(blank=True, null=True)),
                ('Categorias', models.CharField(blank=True, choices=[('Pava', 'Pava'), ('Pijamas', 'Pijamas'), ('Sabanas', 'Sabanas'), ('Camisa manga larga', 'Camisa manga larga'), ('Camisa manga corta', 'Camisa manga corta'), ('Blusa manga larga', 'Blusa manga larga'), ('Pantalon sencillo', 'Pantalon sencillo'), ('Peto', 'Peto'), ('Delantal tipo guitarra', 'Delantal tipo guitarra'), ('Saco', 'Saco'), ('Delantal de linea', 'Delantal de linea'), ('Panalon dama', 'Pantalon dama'), ('Pantalon hombre', 'Pantalon hombre'), ('Overol sencillo', 'Overol sencillo'), ('Campo con ojo', 'Campo con ojo'), ('Blue jean', 'Blue jean'), ('Tapabocas', 'Tapabocas'), ('Cachucha', 'Cachucha'), ('Bombacho', 'Bombacho'), ('Mangas', 'Mangas'), ('Sudadera', 'Sudadera'), ('Gorro', 'Gorro'), ('Bermuda indigo', 'Bermuda indigo'), ('Bata', 'Bata'), ('Cobija', 'Cobija'), ('Funda', 'Funda'), ('Envolvedera', 'Envolvedera'), ('Pañuelo', 'Pañuelo'), ('Chompa', 'Chompa'), ('Tula', 'Tula'), ('Pantaloneta', 'Pantaloneta'), ('Talego', 'Talego'), ('Bolsillo G21', 'Bolsillo G21')], max_length=100)),
                ('Ficha', models.FileField(upload_to='fichas/')),
                ('Ultima_actualizacion', models.DateField(auto_now=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prendas', to='proveedor.proveedor')),
            ],
        ),
    ]
