# Generated by Django 5.2.4 on 2025-07-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0002_alter_proveedor_textilera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenda',
            name='Categorias',
            field=models.CharField(blank=True, choices=[('Pava', 'Pava'), ('Pijamas', 'Pijamas'), ('Sabanas', 'Sabanas'), ('Camisa manga larga', 'Camisa manga larga'), ('Camisa manga corta', 'Camisa manga corta'), ('Blusa manga larga', 'Blusa manga larga'), ('Pantalon sencillo', 'Pantalon sencillo'), ('Peto', 'Peto'), ('Delantal tipo guitarra', 'Delantal tipo guitarra'), ('Saco', 'Saco'), ('Delantal de linea', 'Delantal de linea'), ('Panalon dama', 'Pantalon dama'), ('Pantalon hombre', 'Pantalon hombre'), ('Overol sencillo', 'Overol sencillo'), ('Campo con ojo', 'Campo con ojo'), ('Blue jean', 'Blue jean'), ('Tapabocas', 'Tapabocas'), ('Cachucha', 'Cachucha'), ('Calzado', 'Calzado'), ('Bombacho', 'Bombacho'), ('Mangas', 'Mangas'), ('Sudadera', 'Sudadera'), ('Gorro', 'Gorro'), ('Bermuda indigo', 'Bermuda indigo'), ('Bata', 'Bata'), ('Cobija', 'Cobija'), ('Funda', 'Funda'), ('Envolvedera', 'Envolvedera'), ('Pañuelo', 'Pañuelo'), ('Chompa', 'Chompa'), ('Tula', 'Tula'), ('Pantaloneta', 'Pantaloneta'), ('Talego', 'Talego'), ('Bolsillo G21', 'Bolsillo G21')], max_length=100),
        ),
    ]
