# Generated by Django 5.2.5 on 2025-08-12 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tela',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Codigo', models.CharField(max_length=100)),
                ('Tela', models.CharField(max_length=255)),
                ('Precio', models.DecimalField(decimal_places=0, max_digits=10)),
                ('FechaEdicion', models.DateTimeField(auto_now=True)),
                ('Ancho', models.DecimalField(decimal_places=0, max_digits=10)),
                ('Inventario', models.DecimalField(decimal_places=0, max_digits=10)),
                ('Disponible', models.DecimalField(decimal_places=0, max_digits=10)),
                ('Estado', models.BooleanField(default=True)),
                ('Categoria', models.CharField(choices=[('Anifluidos', 'Anifluidos'), ('Dacron', 'Dacron'), ('Drill', 'Drill'), ('Entretela', 'Entretela'), ('Flex', 'Flex'), ('Gabardina', 'Gabardina'), ('Genero', 'Genero'), ('Indigo', 'Indigo'), ('Oxford', 'Oxford'), ('Rib', 'Rib'), ('Twill', 'Twill')], max_length=100)),
                ('Proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telas', to='proveedor.proveedor')),
            ],
        ),
    ]
