# Generated by Django 5.2.4 on 2025-07-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tela',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Codigo', models.CharField(max_length=100)),
                ('Tela', models.CharField(max_length=255)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('FechaEdicion', models.DateTimeField(auto_now=True)),
                ('Ancho', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Inventario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Disponible', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
