# Generated by Django 5.2.4 on 2025-07-31 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0003_alter_prenda_categorias'),
        ('telas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tela',
            name='Proveedor',
            field=models.ForeignKey(default=312, on_delete=django.db.models.deletion.CASCADE, related_name='telas', to='proveedor.proveedor'),
            preserve_default=False,
        ),
    ]
