# Generated by Django 5.2.4 on 2025-07-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telas', '0002_tela_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tela',
            name='Categoria',
            field=models.CharField(choices=[('Algodon', 'Algodón'), ('Seda', 'Seda'), ('Lino', 'Lino'), ('Poliester', 'Poliéster'), ('Mezcla', 'Mezcla')], default=3233, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tela',
            name='Estado',
            field=models.BooleanField(default=True),
        ),
    ]
