# Generated by Django 5.2.4 on 2025-07-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('inventario', models.IntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=12)),
                ('fecha_edicion', models.DateField(auto_now=True)),
                ('categoria', models.CharField(choices=[('cintas', 'Cintas'), ('cierres', 'Cierres'), ('botones', 'Botones'), ('velcros', 'Velcros'), ('sesgos', 'Sesgos'), ('broches', 'Broches'), ('cordones', 'Cordones'), ('elasticos', 'Elasticos'), ('deslizadores', 'Deslizadores'), ('fusionados', 'Fusionados'), ('corte', 'Corte'), ('forros', 'Forros'), ('lavados', 'Lavados')], max_length=50)),
            ],
        ),
    ]
