# Generated by Django 5.2.4 on 2025-07-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumos',
            name='inventario',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
