# Generated by Django 5.2.5 on 2025-08-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nit', models.CharField(max_length=9, unique=True)),
                ('Razon', models.CharField(max_length=200, verbose_name='Razón social')),
                ('Nombre', models.CharField(max_length=100)),
                ('Sigla', models.CharField(blank=True, max_length=20)),
                ('Ciudad', models.CharField(max_length=100)),
                ('Direccion', models.CharField(max_length=200)),
                ('Telefono', models.CharField(blank=True, max_length=20)),
                ('Celular', models.CharField(blank=True, max_length=20)),
                ('Contacto', models.CharField(blank=True, max_length=100)),
                ('Cargo', models.CharField(blank=True, max_length=100)),
                ('Correo', models.EmailField(max_length=100)),
                ('CorreoExtra', models.EmailField(blank=True, max_length=100)),
                ('CorreoFactura', models.EmailField(blank=True, max_length=100)),
                ('Sector', models.CharField(choices=[('', 'Seleccione'), ('industrial', 'Industrial'), ('comercial', 'Comercial'), ('educativo', 'Educativo'), ('salud', 'Salud'), ('gubernamental', 'Gubernamental'), ('otro', 'Otro')], default='', max_length=50)),
                ('Productos', models.CharField(choices=[('', 'Seleccione'), ('Camisetas', 'Camisetas'), ('Calzado de agencias', 'Calzado de agencias'), ('Calzado Kondor', 'Calzado Kondor'), ('EPP', 'EPP'), ('Prendas de cabeza', 'Prendas de cabeza')], default='', max_length=50)),
                ('Pagina', models.CharField(blank=True, max_length=200)),
                ('Estado', models.CharField(choices=[('', 'Seleccione'), ('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Omitir', 'Omitir'), ('liquidado', 'Liquidado')], default='', max_length=20)),
                ('Vendedor', models.CharField(choices=[('', 'Seleccionar'), ('Elizabeth Quintero Ramírez', 'Elizabeth Quintero Ramírez'), ('María Zulima Alvaran', 'María Zulima Alvaran'), ('Luz Extela Berrio Pino', 'Luz Extela Berrio Pino'), ('Luz Daniela Orozco Mesa', 'Luz Daniela Orozco Mesa'), ('Gladys Patricia Montoya Rúa', 'Gladys Patricia Montoya Rúa'), ('María Parra Restrepo', 'María Parra Restrepo'), ('Andres Felipe Alvarez', 'Andres Felipe Alvarez'), ('Aura Vanessa López García', 'Aura Vanessa López García'), ('María Parra Restrepo', 'María Parra Restrepo'), ('Ventas directas', 'Ventas directas'), ('Prospectos generales', 'Prospectos generales')], default='', max_length=50)),
                ('TipoContacto', models.CharField(choices=[('', 'Seleccionar'), ('Correo electronico', 'Correo electronico'), ('Llamada telefonica', 'Llamada telefonica'), ('WhatsApp', 'WhatsApp')], default='', max_length=50)),
                ('Comentario', models.TextField(blank=True)),
            ],
        ),
    ]
