# Generated by Django 5.2.5 on 2025-08-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='Productos',
            field=models.TextField(blank=True),
        ),
    ]
