# Generated by Django 5.2.4 on 2025-07-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='Pagina',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
